'use client'

import { useEffect, useRef, useState } from 'react'
import { ArrowRight, FileText, Upload } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { api, ApiError, Project, Snapshot } from '@/lib/api'

export default function NewVerificationPage() {
 const router=useRouter(), [rows,setRows]=useState<{project:Project;snapshot:Snapshot}[]>([]),[selected,setSelected]=useState(''),[change,setChange]=useState(''),[plan,setPlan]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),file=useRef<HTMLInputElement>(null)
 useEffect(()=>{ void (async()=>{try{const ps=await api.projects();const pairs=await Promise.all(ps.map(async project=>({project,snapshot:(await api.snapshots(project.id))[0]})));setRows(pairs.filter(x=>x.snapshot?.status==='READY') as {project:Project;snapshot:Snapshot}[])}catch(e){setError(e instanceof ApiError?e.message:'Could not load snapshots.')}finally{setLoading(false)}})()},[])
 const start=async()=>{setError(''); const row=rows.find(x=>x.snapshot.id===selected);if(!row||!change.trim()||!plan.trim()){setError('Select a READY snapshot and provide both change request and plan.');return}try{const version=await api.createPlan(row.project.id,{change_request:change,candidate_plan:plan});const run=await api.createRun({project_id:row.project.id,snapshot_id:row.snapshot.id,plan_version_id:version.id});router.push(`/workspace/runs/${run.id}`)}catch(e){setError(e instanceof ApiError?e.message:'Could not queue verification.')}}
 return <div><div className="page-header-block"><div className="preflight-eyebrow"><FileText size={13}/><span>PRE-FLIGHT VERIFICATION</span></div><h1 className="page-main-title">Verify an engineering plan</h1><p className="page-main-desc">PlanProof will automatically extract claims and turn them into testable proof obligations.</p></div><div className="dashboard-two-col-grid"><div className="card-panel-white"><div className="form-field-block"><label className="form-field-label">Target READY snapshot</label><select disabled={loading} className="custom-select-box" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{loading?'Loading snapshots…':'Select repository snapshot'}</option>{rows.map(({project,snapshot})=><option key={snapshot.id} value={snapshot.id}>{project.repository_source_type==='seeded_fixture'?'Demo fixture — ':''}{project.name} · {snapshot.resolved_commit_sha?.slice(0,7)}</option>)}</select></div><div className="form-field-block"><label className="form-field-label">What are you planning to change?</label><input className="custom-text-input" value={change} maxLength={20000} onChange={e=>setChange(e.target.value)} placeholder="Describe the engineering change..."/></div><div className="form-field-block"><label className="form-field-label">Candidate plan</label><div style={{display:'flex',justifyContent:'flex-end'}}><input ref={file} type="file" accept=".md,.txt,.json,.yaml,.yml" hidden onChange={e=>{const f=e.target.files?.[0];if(f)f.text().then(setPlan)}}/><button type="button" className="btn-plan-action" onClick={()=>file.current?.click()}><Upload size={12}/>Upload plan</button></div><textarea className="custom-textarea" rows={10} value={plan} maxLength={50000} onChange={e=>setPlan(e.target.value)} placeholder="Paste an engineering plan…"/></div>{error&&<p style={{color:'#B91C1C'}}>{error}</p>}<button className="btn-verify-plan-cta" onClick={start}>Verify this plan <ArrowRight size={14}/></button></div><div className="right-stack-col"><div className="what-next-card"><h3 className="card-heading-compact">What happens next</h3><p>1. Extract claims</p><p>2. Gather deterministic repository evidence</p><p>3. Apply the server-authoritative plan gate</p></div></div></div></div>
}
