steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_PLANPROOF_API_URL=$_API_URL'
      - '-t'
      - '$_IMAGE'
      - '-f'
      - 'Dockerfile'
      - '.'
images:
  - '$_IMAGE'
