'use client'

import { useEffect, useState } from 'react'
import { GitBranch, Layers3, Plus } from 'lucide-react'
import { api, ApiError, Project, Snapshot } from '@/lib/api'

type Entry = { project: Project; snapshot?: Snapshot }
export default function RepositoriesPage() {
  const [items, setItems] = useState<Entry[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [adding, setAdding] = useState(false), [type, setType] = useState<'public_github' | 'seeded_fixture'>('public_github'), [url, setUrl] = useState(''), [ref, setRef] = useState('main'), [name, setName] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const projects = await api.projects(); const rows = await Promise.all(projects.map(async project => ({ project, snapshot: (await api.snapshots(project.id))[0] }))); setItems(rows) } catch (e) { setError(e instanceof ApiError ? e.message : 'Could not load repositories.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const add = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const project = await api.createProject(type === 'public_github' ? { name: name || url, owner_id: 'local-session', repository_source: { type, repository_url: url, requested_ref: ref || undefined } } : { name: name || 'Partial Refund Demo', owner_id: 'local-session', repository_source: { type, fixture_id: 'partial-refunds-v1' } }); await api.createSnapshot(project.id); setAdding(false); setUrl(''); setName(''); await load() } catch (e) { setError(e instanceof ApiError ? e.message : 'Could not add repository.') } }
  return <div>
    <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:20, gap:12 }}><div><div className="preflight-eyebrow"><Layers3 size={13}/><span>REPOSITORIES</span></div><h1 className="page-main-title">Repositories</h1><p className="page-main-desc">Immutable snapshots are the source of truth for every verification.</p></div><button className="btn-verify-plan-cta" onClick={()=>setAdding(!adding)}><Plus size={15}/>{adding?'Close':'Add public repository'}</button></div>
    {adding && <form onSubmit={add} className="card-panel-white" style={{ marginBottom:18 }}><div className="form-field-block"><label className="form-field-label">Repository source</label><select className="custom-select-box" value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="public_github">Public GitHub repository</option><option value="seeded_fixture">Demo fixture — partial refunds</option></select></div>{type==='public_github' && <><div className="form-field-block"><label className="form-field-label">Public GitHub URL</label><input required className="custom-text-input" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/OWNER/REPOSITORY"/></div><div className="form-field-block"><label className="form-field-label">Requested ref (optional)</label><input className="custom-text-input" value={ref} onChange={e=>setRef(e.target.value)} placeholder="main"/></div></>}<div className="form-field-block"><label className="form-field-label">Display name (optional)</label><input className="custom-text-input" value={name} onChange={e=>setName(e.target.value)}/></div><button className="btn-verify-plan-cta" type="submit"><GitBranch size={14}/>Create and index snapshot</button></form>}
    {error && <div className="card-panel-white" style={{ color:'#B91C1C', marginBottom:16 }}>{error} <button className="btn-plan-action" onClick={()=>void load()}>Retry</button></div>}
    {loading ? <div className="card-panel-white">Loading repositories…</div> : items.length===0 ? <div className="card-panel-white" style={{ textAlign:'center', padding:56 }}><h2>No repositories connected</h2><p>Connect GitHub to start verifying plans.</p></div> : <div style={{ display:'grid', gap:12 }}>{items.map(({project,snapshot})=><div key={project.id} className="card-panel-white" style={{ display:'flex', justifyContent:'space-between', gap:16 }}><div><strong>{project.name}</strong><p style={{ fontSize:12, color:'#64748B' }}>{project.repository_source_type==='seeded_fixture' ? 'Demo fixture' : project.repository_url}</p><span className="commit-mini-tag">{snapshot?.resolved_commit_sha?.slice(0,7) || 'Resolving'}</span> <span style={{ fontSize:11 }}>{snapshot?.requested_ref || project.requested_ref || 'default ref'}</span></div><div style={{ textAlign:'right', fontSize:12 }}><strong>{snapshot?.status || 'No snapshot'}</strong><p>{snapshot?.files_indexed ?? 0} files · {snapshot?.symbols_indexed ?? 0} symbols</p><p>{snapshot?.supported_languages?.join(', ') || 'Indexing pending'}</p></div></div>)}</div>}
  </div>
}
